[plugin]
repository = "https://github.com/RokasKil/TitleEdit.git"
commit = "136193fdc07bdd53c8fdb3faea537fb88c47492f"
owners = [
    "RokasKil",
]
project_path = "TitleEdit"
changelog = """
- API12 and 7.2 patch update
"""
